Glibc 2.33 fix.
The library does not declare __fxstatat64 and friends in a header file.
Thus the following warning appears:

```
libsystem.c:333:1: error: no previous prototype for '__xstat' [-Werror=missing-prototypes]
  333 | __xstat (int version, const char *path, struct stat *buf)
      | ^~~~~~~
libsystem.c:342:1: error: no previous prototype for '__xstat64' [-Werror=missing-prototypes]
  342 | __xstat64 (int version, const char *path, struct stat64 *buf)
      | ^~~~~~~~~
libsystem.c:351:1: error: no previous prototype for '__fxstatat' [-Werror=missing-prototypes]
  351 | __fxstatat(int ver, int dirfd, const char *pathname, struct stat *buf, int flags)
      | ^~~~~~~~~~
libsystem.c:360:1: error: no previous prototype for '__fxstatat64' [-Werror=missing-prototypes]
  360 | __fxstatat64(int ver, int dirfd, const char *pathname, struct stat64 *buf, int flags)
      | ^~~~~~~~~~~~
```

Fixed #167.